version = 0.1

[default.global.parameters]
stack_name = "creative-tester-dev"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "creative-tester-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
resolve_s3 = true
confirm_changeset = true
parameter_overrides = "Stage=dev"
